[package]
name = "molt-app"
version = "0.1.0"
authors = ["Will Duquette <will@wjduquette.com>"]
edition = "2018"

[dependencies]
molt = { path = "../molt" }
molt-shell = { path = "../molt-shell" }

[[bin]]
name = "moltsh"
path = "src/main.rs"
